{% set name = "pyremo" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0a2181f38af6f58360589fdf6c1ce1515bc0afc1d8eb90f051eda05786675645

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - prsint = pyremo.cli:prsint
    - pyremo-analysis = pyremo.cli:main_analysis

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    
  run:
    - python >=3.7
    - numpy >=1.17
    - pooch >=1.0
    - xarray >=0.15
    - py-cordex >=0.4.0
    - xesmf
    - cf_xarray
    - setuptools >=40.4

test:
  imports:
    - pyremo

about:
  home: https://github.com/remo-rcm/pyremo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: processing tools for the regional climate model REMO
  doc_url: https://pyremo.readthedocs.io
  dev_url: https://github.com/remo-rcm/pyremo

extra:
  recipe-maintainers:
    - larsbuntemeyer
