{% set name = "pyremo" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37a0ccdfa71ab86adddb72485f77d56cc9446bede4a3defe11961c5ec9a76865
build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - prsint = pyremo.cli:prsint
    - pyremo-analysis = pyremo.cli:main_analysis
    - pradd-vars = pyremo.cli:add_variables

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm

  run:
    - python >={{ python_min }}
    - numpy <1.26.3
    - pooch >=1.0
    - xarray >=0.20
    - py-cordex >=0.4.0
    - xesmf >=0.7.0
    - cf_xarray >=0.8.1
    - setuptools >=40.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyremo

about:
  home: https://github.com/remo-rcm/pyremo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: processing tools for the regional climate model REMO
  doc_url: https://pyremo.readthedocs.io
  dev_url: https://github.com/remo-rcm/pyremo

extra:
  recipe-maintainers:
    - larsbuntemeyer
