{% set name = "pyremo" %}
{% set version = "0.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 0fc972334dcecb4f152678bc9a20b2d250a246647aa40600959fb8112ad00c97

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    -  "prsint = pyremo.cli:prsint"
    -  "pyremo-analysis = pyremo.cli:main_analysis"

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - numpy >=1.17
    - pooch >=1.0
    - xarray >=0.15
    - py-cordex >=0.4.0
    - xesmf
    - cf_xarray

test:
  imports:
    - pyremo 

about:
  home: https://github.com/remo-rcm/pyremo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "processing tools for the regional climate model REMO"
  doc_url: https://pyremo.readthedocs.io
  dev_url: https://github.com/remo-rcm/pyremo 

extra:
  recipe-maintainers:
    - larsbuntemeyer 
